FROM golang:1.11.10-alpine

RUN apk update && apk add \
    openssh \
    git \
    make \
    bash \
    gcc \
    musl-dev \
    linux-headers \
    apk-tools-static \
    libseccomp \
    libseccomp-dev \
    curl

